openapi: 3.0.0
# Added by API Auto Mocking Plugin
# servers:
#   - description: SwaggerHub API Auto Mocking
#     url: https://virtserver.swaggerhub.com/adiulay/Baggage-Handling/1.0.0
info:
  description: This API receives baggages and assigns it either inbound/outbound
  version: "1.0.0"
  title: Baggage Handling API
  contact:
    email: jtruong20@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: domestic
    description: baggage's inbound outbound for domestic
  - name: international
    description: baggage's inbound outbound for international
paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description:  Gets domestic and international baggages
      responses:
        '200':
          description: Successfully returned a list of baggages events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ReadingStats:
      required:
        - num_domestic_baggages
        - num_international_baggages
        - total_baggages
      properties:
        num_domestic_baggages:
          type: integer
          example: 50000
        num_international_baggages:
          type: integer
          example: 50000
        total_baggages:
          type: integer
          example: 100000
      type: object
        