version: 1
event_domestic:
    url: http://localhost:8090/baggage/domestic
event_international:
    url: http://localhost:8090/baggage/international
events:
    hostname: ec2-52-24-255-57.us-west-2.compute.amazonaws.com
    port: 9092
    topic: events